CREATE DATABASE CIMAJORS;

USE CIMAJORS;

CREATE TABLE STUDENT (
DOLPHIN_ID int(9),
FIRST_NAME varchar(16),
LAST_NAME varchar(32),
PRIMARY KEY (DOLPHIN_ID)
) ENGINE=INNODB;

CREATE TABLE PROGRAM (
PROGRAM_ID int(4),
PROGRAM_NAME varchar(32),
PRIMARY KEY (PROGRAM_ID)
) ENGINE=INNODB;

CREATE TABLE MAJOR (
MAJOR_ID int(4),
MAJOR_NAME varchar(32),
PROGRAM_ID int(4),
PRIMARY KEY (MAJOR_ID),
FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAM(PROGRAM_ID)
) ENGINE=INNODB;

CREATE TABLE STUDENT_MAJOR (
DOLPHIN_ID int(9),
MAJOR_ID int(4),
PRIMARY KEY (DOLPHIN_ID, MAJOR_ID),
FOREIGN KEY (DOLPHIN_ID) REFERENCES STUDENT(DOLPHIN_ID),
FOREIGN KEY (MAJOR_ID) REFERENCES MAJOR(MAJOR_ID)
) ENGINE=INNODB;