CREATE DATABASE CIC;

USE CIC;

CREATE TABLE HOSPITAL (
HOSPITAL_NAME varchar(32),
STREET_ADDRESS varchar(64),
CITY varchar(32),
STATE char(2),
ZIP int(5),
SPECIALTY varchar(32),
PRIMARY KEY (HOSPITAL_NAME)
) ENGINE=INNODB;

CREATE TABLE DRUG (
DRUG_CODE varchar(10),
DRUG_NAME varchar(64),
DRUG_PRICE float(7,2),
PRIMARY KEY (DRUG_CODE)
) ENGINE=INNODB;

CREATE TABLE DOCTOR (
DOC_ID varchar(10),
DOC_LNAME varchar(32),
DOC_FNAME varchar(16),
DOC_INITIAL char(1),
DOC_SPECIALITY varchar(32),
HOSPITAL_NAME varchar(32),
PRIMARY KEY (DOC_ID),
FOREIGN KEY (HOSPITAL_NAME) REFERENCES HOSPITAL(HOSPITAL_NAME)
) ENGINE=INNODB;

CREATE TABLE PATIENT(
PAT_NUM varchar(10),
PAT_TITLE varchar(3),
PAT_LNAME varchar(32),
PAT_FNAME varchar(16),
PAT_INITIAL char(1),
PAT_DOB date,
PAT_AREACODE char(3) CHECK (PAT_AREACODE IN ('209','213','279','310','323','341','408','415','424','442','510','530','559','562','619','626','628','650','657','661','669','707','714','747','760','805','818','820','831','840','858','909','916','925','949','951')),
PAT_PHONE char(8),
PRIMARY KEY (PAT_NUM)
) ENGINE=INNODB;

CREATE TABLE PRESCIPTION (
DOC_ID varchar(10),
PAT_NUM varchar(10),
DRUG_CODE varchar(10),
PRES_DOSAGE varchar(64),
PRES_DATE date,
PRIMARY KEY (DOC_ID, PAT_NUM, DRUG_CODE),
FOREIGN KEY (DOC_ID) REFERENCES DOCTOR(DOC_ID),
FOREIGN KEY (PAT_NUM) REFERENCES PATIENT(PAT_NUM),
FOREIGN KEY (DRUG_CODE) REFERENCES DRUG(DRUG_CODE)
) ENGINE=INNODB;

CREATE TABLE APPOINTMENT (
PAT_NUM varchar(10),
DOC_ID varchar(10),
START_TIME datetime,
END_TIME datetime,
HOSPITAL_NAME varchar(32),
LOCATION varchar(32),
PRIMARY KEY (PAT_NUM, DOC_ID, START_TIME),
FOREIGN KEY (PAT_NUM) REFERENCES PATIENT(PAT_NUM),
FOREIGN KEY (DOC_ID) REFERENCES DOCTOR(DOC_ID),
FOREIGN KEY (HOSPITAL_NAME) REFERENCES HOSPITAL(HOSPITAL_NAME),
CONSTRAINT APPT_PAT_TIME UNIQUE (PAT_NUM, START_TIME),
CONSTRAINT APPT_DOC_TIME UNIQUE (DOC_ID, START_TIME)
) ENGINE=INNODB;