CREATE DATABASE CIDOLPHINPODS;

USE CIDOLPHINPODS;

CREATE TABLE STUDENT (
DOLPHIN_ID int(9),
FIRST_NAME varchar(16),
LAST_NAME varchar(32),
PRIMARY KEY (DOLPHIN_ID)
) ENGINE=INNODB;

CREATE TABLE FACULTY (
DOLPHIN_ID int(9),
FIRST_NAME varchar(16),
LAST_NAME varchar(32),
PRIMARY KEY (DOLPHIN_ID)
) ENGINE=INNODB;

CREATE TABLE CSUCI_MEMBER (
DOLPHIN_ID int(9) CHECK (DOLPHIN_ID IN ((SELECT DOLPHIN_ID FROM STUDENT),(SELECT DOLPHIN_ID FROM FACULTY))),
FIRST_NAME varchar(16),
LAST_NAME varchar(32),
CSUCI_MEMBER_TYPE varchar(7) CHECK (CSUCI_MEMBER_TYPE IN("student","faculty")),
PRIMARY KEY (DOLPHIN_ID)
) ENGINE=INNODB;

CREATE TABLE SHUTTLE (
SHUTTLE_ID int(5),
SHUTTLE_SIZE int(12),
PRIMARY KEY (SHUTTLE_ID)
) ENGINE=INNODB;

CREATE TABLE SHUTTLE_TRIP(
TRIP_ID int(10),
SHUTTLE_ID int(5),
DRIVER_ID int(9),
PRIMARY KEY (TRIP_ID),
FOREIGN KEY (SHUTTLE_ID) REFERENCES SHUTTLE(SHUTTLE_ID),
FOREIGN KEY (DRIVER_ID) REFERENCES CSUCI_MEMBER(DOLPHIN_ID)
) ENGINE=INNODB;

CREATE TABLE TRIP_PASSENGER (
PASSENGER_ID int(9),
TRIP_ID int(10),
PRIMARY KEY (PASSENGER_ID, TRIP_ID),
FOREIGN KEY (PASSENGER_ID) REFERENCES CSUCI_MEMBER(DOLPHIN_ID),
FOREIGN KEY (TRIP_ID) REFERENCES SHUTTLE_TRIP(TRIP_ID)
) ENGINE=INNODB;