create database CIA;

use CIA;

CREATE TABLE ARTIST (
ARTIST_ID int(9),
ARTIST_MOTIF varchar(31),
MOTIF_DESCRIPTION varchar(255),
PRIMARY KEY (ARTIST_ID)
) ENGINE=INNODB;

CREATE TABLE GALLERY (
GALLERY_ID int(4),
GALLERY_NAME varchar(32),
GALLERY_LOCATION char(5),
PRIMARY KEY (GALLERY_ID)
) ENGINE=INNODB;

CREATE TABLE PAINTING (
PAINTING_ID int(6),
ARTIST_ID int(9),
GALLERY_ID int(4),
PRICE float(10,7),
PRIMARY KEY (PAINTING_ID),
FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST(ARTIST_ID),
FOREIGN KEY (GALLERY_ID) REFERENCES GALLERY(GALLER_ID)
) ENGINE=INNODB;